### ISSUE TITLE
I'm your fan

### ISSUE THREAD

**Issue by SubinVane** [guestccc/blog#1]
How can I become as good as you and make such a beautiful blog

**Comment by guestccc** [comment]
> How can I become as good as you and make such a beautiful blog

I believe in a word that says "知我所知者，尽善尽美；知我所不知者，虚怀若谷"

**Comment by guestccc** [comment]
@SubinVane 
I believe in a word that says "知我所知者，尽善尽美；知我所不知者，虚怀若谷"
